#Stripe API Secret Key configuration, the default value is a test key, but it's recommended to use your own key for production
stripe.apiKey=${STRIPE_API_KEY:sk_test_51TtJmAR03Sk1d0sXjSLk7ISqC5WBuod4NP6gC5Mx4eir43GEYVDbNQLWVRL2iBpfFifLE5MsqLX5XX70N2iopmyr00OrD2RK5Q}
