logging.level.root=${LOG_LEVEL:WARN}

#define result log file path
logging.file.name=${LOG_FILE_NAME:/Users/mpriharsanto/Downloads/Belajar_Fullstack_React_Springboot/eazystore-log/app-qa.log}

#only use this statements to true in development phase
spring.jpa.show-sql=${JPA_SHOW_URL:false}

#to make sql logs properly formatted
spring.jpa.properties.hibernate.format_sql=${HIBERNATE_FORMAT_URL:false}

contact.phone=+91-1234567891
contact.email=qa@eazystore.com
contact.address=123 Main Street, London, UK